# Generated by Django 6.0.4 on 2026-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exam', 'Exam'), ('assignment', 'Assignment'), ('certificate', 'Certificate'), ('course', 'Course'), ('announcement', 'Announcement')], default='announcement', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('color', models.CharField(default='#1565C0', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
