# Generated by Django 6.0.4 on 2026-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('grade', models.CharField(choices=[('Elite + Gold', 'Elite + Gold'), ('Elite', 'Elite'), ('Silver', 'Silver'), ('Pass', 'Pass')], default='Pass', max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('cert_number', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
