# Generated by Django 6.0.4 on 2026-04-12 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseweek',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='courseweek',
            unique_together={('course', 'week_number')},
        ),
    ]
